version: "3"
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: toni14nexe
      MONGO_INITDB_ROOT_PASSWORD: 4CmjezjVzamLvwBS
